<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.14" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CoreCrossingCuttingConcerns">
      <HintPath>..\..\CorePackages\CoreCrossingCuttingConcerns\bin\Debug\net9.0\CoreCrossingCuttingConcerns.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
